### ISSUE TITLE
Genes not in dbCMMS

### ISSUE THREAD

**Issue by ghost** [robinandeer/scout#97]
Gene not in our database which is showing in list of IEM variants (family 118)
- [ ] FAM131A
- [ ] ECE2: https://clinical-db.scilifelab.se:8081/#/family/137/variants/38820893?database=iem&offset=0&relation=GREATER
- [ ] https://clinical-db.scilifelab.se:8081/#/family/139/variants/32031786?database=iem&offset=0&relation=GREATER
- [ ] GPR15: https://clinical-db.scilifelab.se:8081/#/family/139/variants/32031785?database=iem&offset=0&relation=GREATER
- [ ] SLC26A1
- [ ] FAM170A
- [ ] prr23b in Family 139
- [ ] c16orf89 in Family 139
- [ ] GPR15 in Family 139
- [ ] KBTBD4 in Family 126

submitted by **Nicole Lesko** & **Michaela**.

**Comment by robinandeer** [comment]
This is because FAM131A overlaps with a gene in the IEM list. The variant has two Ensembl IDs (ENSG00000175182, ENSG00000145191) for this reason.

Yes, the gene annotations are not informative in this case, but the variant should still be reported. It's a tricky problem to solve in the pipeline but down the line it should be fixed.

For now I guess we will have to discuss it at a weekly meeting and keep a look out for variants with multiple Ensembl IDs.

**Comment by robinandeer** [comment]
For right now, I will filter them out on the interface level (not research) until we come up with a more permanent solution.
